### ISSUE TITLE
Basic Setup of Boomerang Express

### ISSUE THREAD

**Issue by vigneshshanmugam** [andreas-marschke/boomerang-express#5]
I have couple of open questions on how to get this app running.  I have my node app that is running on port 3000 which loads the boomerang snippet. 

I want to run boomerang express in some other port and start receiving all the data from my node app. Can you tell the basic steps?. Cant able to find the configuration in the doc anywhere.

**Comment by vigneshshanmugam** [comment]
Got the basic app up and running.

**Comment by vigneshshanmugam** [comment]
Cant able to see the metrics for resource timing on log, Only getting response_time value

**Comment by andreas-marschke** [comment]
There's a master.json.example file in `config/` use that to configure boomerang-express. 

Then use one of the 2 backends provided nedb (local json like storage) or connected to a mongodb server. `master.json.example` shows youn how `nedb` is configured. 

Then simply run boomerang-express from the console with `node app.js`.

Be aware that you'll have to have a database directory for `nedb` setup already. You'll also need to assign a `userid` to your beacon-URL. 

A simple setup can be generated for you using grunt from the boomerang-express directory with the command `grunt developer` make sure you have a valid configuration for the grunt-task in `tasks` as `developer.config.json` you can copy it from `developer.config.json.example`.

**Comment by andreas-marschke** [comment]
Can I close this?
